name: Deploy Website

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push version commits
      id-token: write # Required for AWS OIDC (if using)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch full history for version bumping

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: |
            nextjs/package-lock.json
            cdk/package-lock.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install deps and build Next.js static export
        working-directory: nextjs
        run: |
          npm ci
          npm run build

      - name: Install CDK deps and build
        working-directory: cdk
        run: |
          npm ci
          npm run build

      - name: CDK Deploy
        working-directory: cdk
        run: npx cdk deploy --require-approval never

